### ISSUE TITLE
Incorrect Coursier cache location for protoc file.

### ISSUE THREAD

**Issue by iron9light** [scalapb/protoc-bridge#236]
I'm using environment variable `COURSIER_CACHE` to control the Coursier cache location.
But it seems protoc-bridge will download protoc to a folder in my project folder:
+ `./null/protocbridge/protocbridge/cache/v1/protoc-windows-x86_64-3.19.1.exe`
+ `./null/protocbridge/protocbridge/cache/v1/protoc-windows-x86_64-3.19.1.exe.complete`

OS: Windows 10
sbt version: 1.5.7
sbt-protoc version: 1.0.5

I found that, 
```scala
ProjectDirectories
  .from("com.thesamet.scalapb", "protocbridge", "protocbridge")
  .cacheDir
```
and
```scala
CacheDefaults.location // used by Fetch class
```

Will use different ways to calculate the base path.

**Comment by thesamet** [comment]
protoc-bridge relies on coursier to download files, and may find files in coursier's cache, but then it makes a copy into its own cache. The reason is that protocbridge needs to set the executable bit on the downloaded files and making that change on coursier's cache may have unintended consequences. There is a way to set protoc-bridge cache through environment variables and system properties as described here: https://github.com/thesamet/sbt-protoc/blob/master/CHANGELOG.md#100-rc3
